language: node_js
node_js:
  - "13"
dist: trusty

branches:
  only:
  - travis_ci_cd

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --base-href https://pamasse.github.io/zonemaster-gui/


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/
  on:
    branch: travis_ci_cd