language: node_js
node_js:
  - "13"
dist: trusty

branches:
  only:
  - travis_ci_cd

before_script:
  - npm install -g @angular/cli

script:
- ng lint
- ng build --prod --base-href https://pamasse.github.io/zonemaster-gui/