language: node_js

node_js:
  - "13"

dist: trusty
sudo: false

env:
  global:
    - MOZ_HEADLESS=1
addons:
  firefox: latest
  chrome: stable


cache:
  directories:
     - ./node_modules

branches:
  only:
  - travis_ci_cd

before_script:
  - npm install

script:
  # - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  # - npm run e2e -- --protractor-config=./protractor.conf.js
  - npm run build:github_page
  - npm run build:release

before_deploy:
  - export RELEASE_TITLE=$(date '+%Y%m%d%H%M%S')-$TRAVIS_JOB_NUMBER-$TRAVIS_TAG

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist/
    on:
      branch: travis_ci_cd
  - provider: releases
    github_token: $GITHUB_TOKEN
    file: "zonemaster_web_gui.zip"
    skip_cleanup: true
    draft: true
    name: $RELEASE_TITLE
    body: "Bla bla bla this is a test :)"
    on:
      branch: travis_ci_cd
      tags: true
